name: NodeJS with Webpack

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm test
      
