name: NodeJS with Webpack

on:
  schedule:
  - cron:  '*/5 * * * *'
    
jobs:
  build:
    name: testing
    runs-on: ubuntu-latest
    
    steps:
      - name: npm install, build and test
        run:  npm install
